config/routes.rb
Rails.application.routes.draw do
  resources :courses
  devise_for :users
  resources :topics
  resources :categories
  resources :entries do
   member do
    put "like", to: "entries#upvote"
    put "dislike", to: "entries#downvote"
  end
 end
  resources :pages
  
 authenticated :user do

  root "static_pages#portal"
end 
unauthenticated :user do
  root "pages#index"
end
  get "static_pages/portal"
    get 'pages/index'
    get 'static_pages/myresources'
    get 'static_pages/favorites'




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def portal
		@courses = Course.all
	end
	def myresources
		if user_signed_in?
			@entries = current_user.entries
		else
			redirect_to new_user_session_path, alert: "You'll need to sign in to view this page."
		end
	end
	def favorites
		if user_signed_in?
			@entries = current_user.find_up_voted_items
		else
			redirect_to new_user_session_path, alert: "You'll need to sign in to view this page."
		end
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/favorites.html.erb
 <div class="myresources-container">
   <h1><span style="color:#409155"><i class="fas fa-heart"></i></span> Favorite Resources</h1>
      

  <div class="my-resource-box">
        <% @entries.each do |entry| %>
        <div class="resource-box single-box">
              <ul>
                <li class="name"><h3><%= link_to entry.title, entry %></h3></li>
               <% if entry.attachment? %>
                <li>
                  <i class="material-icons">attach_file</i>
                   <%= link_to entry.attachment.file.filename, entry.attachment_url if entry.attachment? %> <br>

                   <% if entry.url_link? %>
                   <a target = "blank" href="<%= entry.url_link %>"><%= entry.url_link %></a>
                  <% end %> <!--/entry attachment exists? -->
                   <% end %>
                </li>
              </ul>
            <div class="bottom">
               <div class="likes">
       <%= link_to like_entry_path(entry), method: :put do %>
                <i class="fas fa-thumbs-up"></i>
                <%= entry.get_upvotes.size %>
              <% end %>
              &nbsp; 
              &nbsp;

              <%= link_to dislike_entry_path(entry), method: :put do %>
                <i class="fas fa-thumbs-down"></i>

                <%= entry.get_downvotes.size %>
              <% end %>
        </div>
              <ul class="bottom-links">
               
              <li><%= link_to 'View Resource', entry %></td> <% if current_user.try(:admin) or current_user == entry.user %> | </li>
          
            <li><%= link_to 'Edit', edit_entry_path(entry) %> | </li> 
            <li><%= link_to 'Delete', entry, method: :delete, data: { confirm: 'Are you sure?' } %></li>
          </ul>
          <% end %>
              <p class="contributor">Contributed by: <%= entry.user.email %></p>
        </div><!--/bottom-->
          </div><!--/resource-box-->
        <% end %>
      </div><!--/my-resource-box-->
      </div><!--/container-->

app/views/static_pages/myresources.html.erb
 <div class="myresources-container">
   <h1><span style="color:#409155"><%= current_user.email %>'s</span> Resources</h1>
  <div class="my-resource-box">
        <% @entries.each do |entry| %>
        <div class="resource-box single-box">
              <ul>
                <li class="name"><h3><%= link_to entry.title, entry %></h3></li>
               <% if entry.attachment? %>
                <li>
                  <i class="material-icons">attach_file</i>
                   <%= link_to entry.attachment.file.filename, entry.attachment_url if entry.attachment? %> <br>

                   <% if entry.url_link? %>
                   <a target = "blank" href="<%= entry.url_link %>"><%= entry.url_link %></a>
                  <% end %> <!--/entry attachment exists? -->
                   <% end %>
                </li>
              </ul>
              <ul class="bottom-links">
              <li><%= link_to 'View Resource', entry %></td> <% if current_user.try(:admin) or current_user == entry.user %> | </li>
          
            <li><%= link_to 'Edit', edit_entry_path(entry) %> | </li> 
            <li><%= link_to 'Delete', entry, method: :delete, data: { confirm: 'Are you sure?' } %></li>
          </ul>
          <% end %>
              <p class="contributor">Contributed by: <%= entry.user.email %></p>
          </div><!--/resource-box-->
        <% end %>
      </div><!--/my-resource-box-->
      </div><!--/container-->

 <script type ="text/javascript">

 document.getElementById("running-total").innerHTML =$('.resource-box').length
</script>
<script type = "text/javascript">
var userList = new List('all-resources', { 
  valueNames: ['name', 'topic', 'type', 'level'],
   page: 8,
  pagination: true,
  size: true

});
</script>

 <script type ="text/javascript">
  $( ".fuzzy-search" ).keyup(function() {

        document.getElementById("running-total").innerHTML =$('.resource-box').length

});


</script>

app/views/static_pages/portal.html.erb
<div class="portal">

	<!-- <div class="top-portal-section">

			<div class="course">
				<i style="font-size: 7rem" class="fas fa-users"></i>


				<h1>Explore By Course</h1>
				<div class="bottom-border"></div>
				<div class="course-flex">
				<%= link_to '/entries?by_courses[]=1' do %>
					<div class="course-box">
						<h3>TECM 2700</h3> Technical Writing
					</div>
				<% end %>
				<%= link_to '/entries?by_courses[]=2' do %>
					<div class="course-box">
						<h3>TECM 2800</h3> The Profession of Technical Communication
					</div>
				<% end %>
				<%= link_to '/entries?by_courses[]=3' do %>
					<div class="course-box">
						<h3>TECM 3100</h3> Visual Technical Communication
					</div>
				<% end %>
				<%= link_to '/entries?by_courses[]=4' do %>
					<div class="course-box">
						<h3>TECM 3200</h3> Information Design for Electronic Media
					</div>
				<% end %>
				<%= link_to '/entries?by_courses[]=5' do %>
					<div class="course-box">
						<h3>TECM 3500</h3> Digital Media for Professional Communication
					</div>
				<% end %>
				<%= link_to '/entries?by_courses[]=6' do %>
					<div class="course-box">
						<h3>TECM 3550</h3> Content Strategy in Technical Communication
					</div>
				<% end %>
				<%= link_to '/entries?by_courses[]=7' do %>
					<div class="course-box">
						<h3>TECM 4100</h3> Writing Proposals
					</div>
				<% end %>
				<%= link_to '/entries?by_courses[]=8' do %>
					<div class="course-box">
						<h3>TECM 4180</h3> Advanced Technical Communication
					</div>
				<% end %>
				<%= link_to '/entries?by_courses[]=9' do %>
					<div class="course-box">
						<h3>TECM 4190</h3> Technical Editing
					</div>
				<% end %>
					<%= link_to '/entries?by_courses[]=10' do %>
					<div class="course-box">
						<h3>TECM 4250</h3> Writing Technical Manuals & Procedures
					</div>
				<% end %>
				<%= link_to '/entries?by_courses[]=11' do %>
					<div class="course-box">
						<h3>TECM 4300</h3> Usability & User Experience
					</div>
				<% end %>
				<%= link_to '/entries?by_courses[]=12' do %>
					<div class="course-box">
						<h3>TECM 4400</h3> Advanced Information Design
					</div>
				<% end %>
				<%= link_to '/entries?by_courses[]=13' do %>
					<div class="course-box">
						<h3>TECM 4500</h3> Content Analysis
					</div>
				<% end %>
			
			
				
				<%= link_to '/entries?by_courses[]=14' do %>
					<div class="course-box">
						<h3>TECM 4700</h3> Science Writing
					</div>
				<% end %>




				</div> --> <!--/course-flex-->
		</div><!--/course-->

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner">
  	  <div class="carousel-item active">
	<%= image_tag("all.jpg", :alt => "audience image", class:'d-block w-100 hero-slide') %>       
	<div class="slide-text col-md-4 p-3 d-flex align-items-center">
		<div>
	    	<h1>Ready to take command of your classroom?</h1>
	    	<br>
	    	<%= link_to "Explore All Resources", entries_path, class: 'btn btn-primary' %>
    	</div>
  	</div>
  </div>
    <div class="carousel-item">
		<%= image_tag("syllabus.jpg", :alt => "audience image", class:'d-block w-100 hero-slide') %>
	<div class="slide-text col-md-4 p-3 d-flex flex-column justify-content-center">
    		<h5>Tech Comm Syllabi</h5>
   			 <p>Looking for a syllabus for a course you've never taught?</p>
  		</div>
    </div>
  
    <div class="carousel-item">
      <img class="d-block w-100" src="..." alt="Third slide">
       <div class="carousel-caption d-none d-md-block">
    <h5>...</h5>
    <p>...</p>
  </div>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
			
<div class="top-portal-section topic">
	<div class="grid">
			<figure class="effect-lily">
				<%= image_tag("audience.jpg", :alt => "audience image") %>
					<figcaption>
						<h2>Audience <span>Analysis</span></h2>
						<p>Explore resources related to audience.</p>
						<a href="#">View more</a>
					</figcaption>			
				</figure>

			<figure class="effect-lily">
				<%= image_tag("audience.jpg", :alt => "audience image") %>
					<figcaption>
						<h2>Visual <span>Design</span></h2>
						<p>Explore resources related to visual design.</p>
						<a href="#">View more</a>
					</figcaption>			
				</figure>
	</div><!--grid-->
			<!--<div class="course">
				<i style = "font-size: 7rem" class="fas fa-folder-open"></i>

				<h1>Popular Topics</h1>
				<div class="bottom-border"></div>
				<div class="course-flex">
				<%= link_to '/entries?by_topics[]=9' do %>
					<div class="course-box">
						<h3>Audience Analysis</h3>
					</div>
				<% end %>
				<%= link_to '/entries?by_topics[]=14' do %>
					<div class="course-box">
						<h3>Data Viz</h3>
					</div>
				<% end %>
				<%= link_to '/entries?by_topics[]=6' do %>
					<div class="course-box">
						<h3>Design</h3>
					</div>
				<% end %>
				<%= link_to '/entries?by_topics[]=2' do %>
					<div class="course-box">
						<h3>Editing</h3>
					</div>
				<% end %>
				<%= link_to '/entries?by_topics[]=1' do %>
					<div class="course-box">
						<h3>Manuals/Procedure</h3>
					</div>
				<% end %>
				<%= link_to '/entries?by_topics[]=8' do %>
					<div class="course-box">
						<h3>Research</h3>
					</div>
				<% end %>
				<%= link_to '/entries?by_topics[]=13' do %>
					<div class="course-box">
						<h3>Software</h3>
					</div>
				<% end %>
				<%= link_to '/entries?by_topics[]=3' do %>
					<div class="course-box">
						<h3>Teamwork</h3>
					</div>
				<% end %>
				<%= link_to '/entries?by_topics[]=12' do %>
					<div class="course-box">
						<h3>TC Profession</h3>
					</div>
				<% end %>
					<%= link_to '/entries?by_topics[]=5' do %>
					<div class="course-box">
						<h3>Usability/UX</h3>
					</div>
				<% end %>
				<%= link_to '/entries?by_topics[]=7' do %>
					<div class="course-box">
						<h3>Web Design</h3>
					</div>
				<% end %>
				
				</div>--><!--/course-flex-->
		</div><!--/course-->
		</div><!--/top-portal-section-->

</div><!--/portal-->