config/routes.rb
Rails.application.routes.draw do
  resources :courses
  devise_for :users
  resources :topics
  resources :categories
  resources :entries do
   member do
    put "like", to: "entries#upvote"
    put "dislike", to: "entries#downvote"
  end
 end
  resources :pages
  
 authenticated :user do

  root "static_pages#portal"
end 
unauthenticated :user do
  root "pages#index"
end
  get "static_pages/portal"
    get 'pages/index'
    get 'static_pages/myresources'
    get 'static_pages/favorites'




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/academic_level.rb
class AcademicLevel < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :entries
	belongs_to :user
end

app/models/course.rb
class Course < ApplicationRecord
	has_many :entries
	belongs_to :user
end

app/models/entry.rb
class Entry < ApplicationRecord
	mount_uploader :attachment, AttachmentUploader

	has_many :entry_topics
  	has_many :topics, through: :entry_topics

  	has_many :entry_categories
  	has_many :categories, through: :entry_categories

  	has_many :entry_courses
  	has_many :courses, through: :entry_courses
	has_many :favorites
	
	belongs_to :user
	acts_as_votable

	scope :by_categories, ->(ids_ary) { joins(entry_categories: :category).where("categories.id" => ids_ary) }
	scope :by_topics, ->(ids_ary) { joins(entry_topics: :topic).where("topics.id" => ids_ary) }
	scope :by_level, -> level { where(:level => level) }
	scope :by_courses, -> (ids_ary) { joins(entry_courses: :course).where("courses.id" => ids_ary) }

end

app/models/entry_category.rb
class EntryCategory < ApplicationRecord
  belongs_to :entry
  belongs_to :category
end

app/models/entry_course.rb
class EntryCourse < ApplicationRecord
	 belongs_to :entry
  belongs_to :course
end

app/models/entry_topic.rb
class EntryTopic < ApplicationRecord
  belongs_to :entry
  belongs_to :topic
end

app/models/topic.rb
class Topic < ApplicationRecord
	has_many :entries, through: :entry_topics
	has_many :entry_topics
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

     has_many :entries
     has_many :topics
     has_many :categories
  	  acts_as_voter

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def portal
	end

	def index
	end 


end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]
before_action :authenticate_user!, only: [:new, :create, :edit, :update, :index]
  before_action :user_is_current_user, only: [:new, :create, :edit, :update, :destroy]
  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all.order(:name => "ASC")
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
 
  end

  # GET /topics/new
  def new
    @topic = Topic.new(:user => @current_user)
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)
    @topic.user_id = current_user.id

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render :show, status: :created, location: @topic }
      else
        format.html { render :new }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    user = User.find_by_id(@topic.user_id)
   topic = @topic
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { render :show, status: :ok, location: @topic }
      else
        format.html { render :edit }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url, notice: 'Topic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit({entry_ids: []}, :id, :topic_id, :name, :user_id)
    end
    def user_is_current_user
    unless current_user.admin?
      redirect_to(root_url, alert: "Sorry! You can't edit this resource since you didn't create it.") and return
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
def entries_name
  scope = current_scopes.first 
  model = entries_scope_map[scope[0]]
  model.find(scope[1][0]).name
end 

def entries_scope_map
  {by_courses: Course}
end
def entries_topic
  scope = current_scopes.first 
  model = entries_topic_map[scope[0]]
  model.find(scope[1][0]).name
end 

def entries_topic_map
  {by_topics: Topic}
end



end 

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
      <strong>
       #{pluralize(resource.errors.count, "error")} must be fixed
      </strong>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer" role="contentinfo">

				<!-- copyright -->
				<p>
					Copyright UNT Department of Technical Communication
				</p>
				<p>Designed and built by <%=link_to "Chris Lam", 'http://chrislamdesign.com' %></p>
				<!-- /copyright -->
				<div class="contact-info">
					<ul>
						<li>940.565.4458</li>
						<li>tcoffice@unt.edu</li>
						<li>Denton, TX 76201</li>
					</ul>
				</div>
				<div class="social-icons">
					<ul>
						<li><i class="fab fa-facebook"></i></li>
						<li><i class="fab fa-twitter-square"></i></li>
						<li><i class="fab fa-linkedin"></i></li>
					</ul>
				</div>

			</footer>
			<!-- /footer -->
<!-- analytics -->
		<script>
		(function(f,i,r,e,s,h,l){i['GoogleAnalyticsObject']=s;f[s]=f[s]||function(){
		(f[s].q=f[s].q||[]).push(arguments)},f[s].l=1*new Date();h=i.createElement(r),
		l=i.getElementsByTagName(r)[0];h.async=1;h.src=e;l.parentNode.insertBefore(h,l)
		})(window,document,'script','//www.google-analytics.com/analytics.js','ga');
		ga('create', 'UA-XXXXXXXX-XX', 'yourdomain.com');
		ga('send', 'pageview');
		</script>

app/views/layouts/_header.html.erb
<header>
	<div class="logo">
		<div class="circle">
			<%= link_to "UNT TCR", root_path %>
		</div>
		<ul>
			<li>UNT Tech Comm Repository</li>
			<li>A resource for TECM instructors</li>
		</ul>
	</div>
<% if user_signed_in? %>
	<nav class="signed-in">
			<ul>
				<li><i class="fas fa-search"></i>

<%= link_to "Explore", static_pages_portal_path %></li>
				<li><i class="fas fa-file"></i>

<%= link_to 'All Resources', entries_path %>
					

					<li><i class="fas fa-heart"></i>

<%= link_to "Favorites", static_pages_favorites_path %></li>
					<li><%= link_to 'Create', new_entry_path, class: 'btn btn-primary' %></li>
				
				</ul>
			<ul class="bottom-nav">
			<li class="signed-in-text">Signed in as: <%= current_user.email %></li>
		<li class="signed-in-text"><i class="fas fa-folder"></i><%= link_to "My Resources", static_pages_myresources_path %></li>
			<li class="signed-in-text"><%= link_to "Sign Out", destroy_user_session_path,  method: :delete  %></li>
		<% if user_signed_in? && current_user.admin? %>
		
			<li class="signed-in-text"><%= link_to "Resource Types", categories_path %></li>
			<li class="signed-in-text"><%= link_to "Topics", topics_path %></li>
		<% end %>
		</ul>
	</nav>
			<% else %>
			<nav class="signed-out">
				<li><i class="fas fa-search"></i>

<%= link_to "Explore", static_pages_portal_path %></li>
				<li><%= link_to "Sign In", new_user_session_path %></li>
				<li><%= link_to "Register", new_user_registration_path%></li>
			</nav>
			<% end %>
	
</header>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TcTeachingRepository</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet">
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
      <script src="https://unpkg.com/infinite-scroll@3/dist/infinite-scroll.pkgd.min.js"></script>

  </head>

  <body class="Site">
	  	<%= render 'layouts/header' %>
	 <div class="container-fluid">
        <%= render 'layouts/messages' %>
	    <%= yield %>
	 </div>
       <%= render 'layouts/footer' %>

  </body>
</html>

app/views/pages/index.html.erb
<div class="hero">
		<div class="tagline">
			<div class="tagline-container">
			<h1>Explore. Share. Create.</h1>
			<h2>The UNT tech comm repository is a digital space for instructors of technical communication to share their valuable knowledge and resources. The repository allows you to easily filter and search for a project, assignment, syllabus, presentation slides, activity, or approach to teaching that are unique to technical communication.</h2>

			<div class="landing-links">
				<%= link_to "Register", new_user_registration_path, class: 'btn-landing' %>
				<%= link_to "Sign in", new_user_session_path, class: 'btn-landing-reverse' %>

			</div><!--/landing links-->
			<div class="explore">
			<i class="fas fa-search"></i>
<%= link_to "Explore the Repository!", static_pages_portal_path %>
		</div>
		</div><!--/tagline-container-->
		</div><!--/tagline-->

		<div class="hero-image-right">

			<div class="hero-overlay">
				
			</div><!--/hero-overlay-->
		</div><!--/hero-image-right-->
	</div><!--/hero-->